"""empty message

Revision ID: 5df8593dd763
Revises: a9034bd71463
Create Date: 2023-11-30 11:59:52.654182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df8593dd763'
down_revision = 'a9034bd71463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quando', sa.Date(), nullable=True),
    sa.Column('quanto', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('parcelado', sa.Boolean(), nullable=True),
    sa.Column('parcelas', sa.Integer(), nullable=True),
    sa.Column('parcela_repr', sa.String(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('gasto_recorrente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gasto_recorrente_id'], ['gasto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gasto_mensal')
    op.drop_table('gasto_recorrente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto_recorrente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quando', sa.DATE(), nullable=True),
    sa.Column('quanto', sa.FLOAT(), nullable=True),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto_mensal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quando', sa.DATE(), nullable=True),
    sa.Column('quanto', sa.FLOAT(), nullable=True),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.Column('parcelado', sa.BOOLEAN(), nullable=True),
    sa.Column('parcela_repr', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.Column('gasto_recorrente_id', sa.INTEGER(), nullable=True),
    sa.Column('parcelas', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['gasto_recorrente_id'], ['gasto_recorrente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gasto')
    # ### end Alembic commands ###
