"""empty message

Revision ID: 73577db00525
Revises: 
Create Date: 2023-10-03 20:31:43.032282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73577db00525'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto_recorrente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quando', sa.Date(), nullable=True),
    sa.Column('quanto', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quando', sa.Date(), nullable=True),
    sa.Column('quanto', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('parcelado', sa.Boolean(), nullable=True),
    sa.Column('parcela_repr', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('gasto_recorrente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gasto_recorrente_id'], ['gasto_recorrente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto_mensal')
    op.drop_table('gasto_recorrente')
    # ### end Alembic commands ###
