"""empty message

Revision ID: a9034bd71463
Revises: 73577db00525
Create Date: 2023-11-20 19:18:51.030185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9034bd71463'
down_revision = '73577db00525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto_mensal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcelas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto_mensal', schema=None) as batch_op:
        batch_op.drop_column('parcelas')

    # ### end Alembic commands ###
